asdass/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]

main/urls.py
from django.urls import path
from . import views
from .views import TodoUpdateView

app_name="main"

urlpatterns=[
    
            path('',views.index,name='index'),
            path('add/',views.addtodopage,name='addtodo'),
            path('update/<int:pk>',TodoUpdateView.as_view(),name='update'),
            path('delete/<int:id>',views.deletetodo,name='delete')
]   

main/models.py
from django.db import models
import datetime
# Create your models here.


PRIORITY_CHOICES=(
    (1,1),(2,2) , (3,3) ,(4,4) , (5,5)
)


#THE FOLLOWING IS USED TO STORE THE SCHEMA OF THE TABLE THAT WE ARE USING
class Todo(models.Model):
    todo_id=models.AutoField(primary_key=True)  # AUTOMATICALLY INCREMENTED
    todo_desc=models.CharField(max_length=40)   # THE DESCRIPTION OF TODOS
    due_date=models.DateTimeField(default=datetime.datetime.now()) #DATE TO BE COMPLETED DATE TIME FIELD
    priority=models.IntegerField(default=1,choices=PRIORITY_CHOICES) #PRIORITY AN INTEGER
    completed=models.BooleanField(default=False)




    

main/forms.py
from django import forms
from .models import Todo
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout ,Row,Div,Field


class AddTodoForm(forms.ModelForm):

    class Meta:
        model=Todo
        fields=['todo_desc','due_date','priority']

    def __init__(self, *args, **kwargs):
         super(AddTodoForm, self).__init__(*args, **kwargs)
         self.helper=FormHelper(self)
         self.fields['todo_desc'].label=False
         self.fields['due_date'].label=False
         self.fields['priority'].label=False
         
         self.helper.layout=Layout(

             Div(
             Div(Field( 'todo_desc', placeholder="Enter Your current Profession" ),css_class='hunwidth'),
             Div(Field('due_date',placeholder='Enter the Due Date'),css_class='hunwidth'),
             Div(Field('priority'),css_class='hunwidth'),
             
             css_class='col-xl-12',
             ),
             
         )

main/views.py
from django.shortcuts import render,redirect,reverse,HttpResponseRedirect
from .models import Todo
from django.views.generic.edit import UpdateView
from .forms import AddTodoForm



# Create your views here.

def index(request):
    all_todos=Todo.objects.all().order_by('priority')
    return render(request,'main/index.html',{'todos':all_todos})


def addtodopage(request):
    if request.method=='POST':
        form=AddTodoForm(request.POST)
        if form.is_valid():
            todo=form.save(commit=False)
            todo.save()

            return redirect('main:index')
    else:
        form=AddTodoForm()
    return render(request,'main/addform.html',{'form':form})

    

class TodoUpdateView(UpdateView):
    model=Todo
   

    form_class=AddTodoForm

    template_name_suffix='_update_form'

    def get_success_url(self):
        return reverse('main:index')

def deletetodo(request,id):
    todo=Todo.objects.get(todo_id=id)
    todo.delete()
    return HttpResponseRedirect(reverse('main:index'))

    

main/templates/main/addform.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Add Todo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.14/css/mdb.min.css" rel="stylesheet">
  
<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.14/js/mdb.min.js"></script>

<style>
    .hunwidth{
        width:100%;
    }

</style>
</head>
<body>

        <nav class="navbar navbar-dark primary-color">

                <div class="mx-auto">
    
                        <a class="navbar-brand "  href="{% url 'main:index' %}">
                                <img src="https://upload.wikimedia.org/wikipedia/commons/6/67/Microsoft_To-Do_icon.png" height="30" alt="mdb logo">
                            Todo-List
                            </a>
                   
                              
                              
                </div>
                
             
    
                  </nav>

                  <br>
                  <br>
                  <div class="container">
         <div class="row">
             <div class="col-xl-3 col-xs-12"></div>
             <div class="col-xl-6 col-xs-12">

                <div class="card">
                       
                    <div class="card-body card-body-cascade ">
                        <div class="text-center">
                            <h4 class="card-title"><strong>Add New Todo</strong></h4>
                        </div>
                            <br>

                            <form method="POST" action="">
                                    {% csrf_token %}
                            
                                    {{form|crispy }}
                                    <br>
                                    <br>
                                    <button type="submit" class="btn  btn-warning" style="width:100% ;color: #FFA000; border-radius: 30px;"><strong style="font-size:18px;">SAVE</strong></button>
                                </form>

                    </div>
                </div>
             </div>
             <div class="col-xl-3 col-xs-12"></div>
         </div>
        </div>         
    
</body>

</html>

main/templates/main/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Todo List</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.14/css/mdb.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet"> 
</head>
<body style="background-color: #ffffff">

        <nav class="navbar navbar-dark primary-color">

            <div class="mx-auto">

                    <a class="navbar-brand "  href="{% url 'main:index' %}">
                            <img src="https://upload.wikimedia.org/wikipedia/commons/6/67/Microsoft_To-Do_icon.png" height="30" alt="mdb logo">
                        Todo-List
                        </a>
               
                          
                          
            </div>
            
            <ul class="nav navbar-nav">
                    <li class="nav-item"
                    ><a class="nav-link waves-effect waves-light" href="{% url 'main:addtodo' %}">
                            <i class="fa fa-pencil" aria-hidden="true"></i>
                            <strong>ADD TODO</strong>
                   </a></li>
     </ul>
              </nav>

              <br>
              <br>
              <br>

              <div class="row">
                  <div class="col-xl-3"></div>

                  <div class="col-xl-6 col-xs-12">

                        {% for todo  in todos %}
                        <div>
                            <div class="card" style="margin-right:8px;margin-left:8px; background-color:#FFB300">
                                   <!--<h1>{{todo.todo_desc}}</h1> --> 
                                   <div class="card-body" >

                                    
                                    <div class="row">
                                        <div class="col-xl-2" >


                                        </div>
                                        <div class="col-xl-7">
                                            <h4 class="card-header-title" style="font-family: 'Josefin Sans', sans-serif; color: #ffffff; font-weight: bold"><strong>{{todo.todo_desc}}</strong></h4>
                                            <!-- Subtitle -->
                                            <p class="" style="color: #ffffff;"><strong>{{todo.due_date}}</strong></p>
                                            
                                        </div>
                                        <div class="col-xl-3">
                                            <div class="row">
                                                <div class="col"></div>
                                                <div class="col">
                                                        <a href="{%url 'main:delete' id=todo.todo_id %}" style="color:inherit;"><i class="fa fa-trash"  aria-hidden="true"></i></a>
                                                        
                                                        <a href="{%url 'main:update' pk=todo.todo_id %}" style="color:inherit;"><i class="fa fa-refresh" style="margin-left:8px;" aria-hidden="true"></i>   </a>                                                 </div>
                                            </div>
                                        </div>
                                    </div>
                                    
                                   </div>
                            </div>
                            
                        </div>
                        <br>
                        {% endfor %}
                  </div>

                  <div class="col-xl-3"></div>
              </div>

  
    
</body>
</html>

main/templates/main/todo_update_form.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Update Todo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.14/css/mdb.min.css" rel="stylesheet">
   
</head>
<body>

        <nav class="navbar navbar-dark primary-color">

                <div class="mx-auto">
    
                        <a class="navbar-brand "  href="{% url 'main:index' %}">
                                <img src="https://upload.wikimedia.org/wikipedia/commons/6/67/Microsoft_To-Do_icon.png" height="30" alt="mdb logo">
                            Todo-List
                            </a>
                   
                              
                              
                </div>
                
             
                  </nav>
                  <br>
                  <br>
                  <div class="container">
                          <div class="row">
                                  <div class="col-xl-3"></div>
                                  <div class="col-xl-6">
                                                <div class="card">
                                                                <div class="card-body">
                                                                        <div class="text-center">
                                                                                <h4 class="card-title"><strong>Update Todo</strong></h4>
                                                                        </div>
                                                                        <br>
                                                                        <form method="POST" action="">
                                                                                {% csrf_token %}
                                                                        
                                                                                {{form|crispy }}
                                                                                <br>
                                                                                
                                                                                <button type="submit" class="btn  btn-warning" style="width:100% ;color: #FFA000; border-radius: 30px;"><strong style="font-size:18px;">SAVE</strong></button>
                                                                            </form>
                                                                </div>
                                                        </div>
                                  </div>
                                  <div class="col-xl-3"></div>
                          </div>
                  </div>
               

      
    
</body>
</html>